### ISSUE TITLE
Anti-virus give warnings when reading coin-hive link

### ISSUE THREAD

**Issue by koaben** [brampat/security#2]
The file OWASP_Top10_examples.md contains a link anti-virus scanners do not like. This will scare away users, so I would remove it. 

This link: https://coin-hive.com/lib/coinhive.min.js

**Comment by brampat** [comment]
Confirmed. Would you like to fix this issue by converting it to a screengrab?
Pls put screen in pics folder and use descriptive filename.
(hint: I obviously could do this myself, but hey: there's another contributor opportunity here ;-)

**Comment by koaben** [comment]
Looks good now, see this link: https://github.com/koaben/security/blob/master/publications/presentation/OWASP_Top10_examples.md

**Comment by koaben** [comment]
The Anti-virus warnings will be gone after you aprove the pull request:
- https://github.com/brampat/security/pull/3

**Comment by brampat** [comment]
Closed by contribution of @koaben
